### ISSUE TITLE
Incident: sinnerschrader-website-static leaks access tokens

### ISSUE THREAD

**Issue by marionebl** [sinnerschrader/sinnerschrader-website#102]
In case of exceptions during requests to create a new Github release sinnerschrader-website-static leaks an Github access token. This is due to [publish-release](https://github.com/remixz/publish-release) leaking the `Authorization` header in plain text when throwing.

**Example:** 

https://travis-ci.org/sinnerschrader/sinnerschrader-website-static/builds/179470281#L1625

**Issue**:

https://github.com/remixz/publish-release/issues/20

**ToDo**:
- [x] Refresh access token
- [x] Temporarily remove/disable publish-release
- [x] Fix publish-release to mask/exclude authorization header

---
(Token is refreshed)

**Comment by marionebl** [comment]
Contributed fix https://github.com/remixz/publish-release/pull/21

**Comment by marionebl** [comment]
Relase: 1.3.3
https://www.npmjs.com/package/publish-release
